spring.application.name=GestionEtablissement
spring.datasource.url=jdbc:postgresql://localhost:5432/gestionEtablissement
spring.datasource.username=postgres
spring.datasource.password=passer
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

